services:
  postgres:
    image: postgres:latest
    container_name: runnerz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: runnerz
      POSTGRES_USER: das
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - runnerz-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U das -d runnerz"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  runnerz-postgres-data:
